---
auth_enabled: true

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

ruler:
  wal:
    dir: /tmp/loki/ruler-wal
  storage:
    type: s3
    s3:
      bucketnames: loki
      s3forcepathstyle: true
      insecure: true
      endpoint: http://minio:9000
      access_key_id: minio_access_key
      secret_access_key: minio_secret_key
